App\Entity\Image:
  type: entity
  repositoryClass: App\Entity\Repositories\ImageRepository
  table: image
  id:
    id:
      type:      integer
      generator: { strategy: AUTO }
  fields:
    filename:
      type:      string
      length:    255

    # changed when files are uploaded, to force preUpdate and postUpdate to fire
    updated:
      type:      datetime
      nullable:  true

    # ...
  lifecycleCallbacks:
    prePersist: ['lifecycleFileUpload']
    preUpdate:  ['lifecycleFileUpload']